name: vets_uo296434_dart_api
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.0-417.3.beta

dependencies:
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  mongo_dart: ^0.9.1

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
